version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./code:/code
    networks:
      - code-network
networks:
  code-network:
    driver: bridge